before_install:
- gem install bundler
cache: bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: FY47kEekV6PCzYf7m/b891Q6EgZKB59eEQex++XCyth3OhQE3vk+5PZ3Rqec47z8+YYrpHgZ7tCgf2UTqS9Qj+JJE752wIdi8Bi5GGKpY5DXlQ+dNcY3BFArhjs5QuHNRroy1xquCqPHx8yVR/5Rt1rOo09Kcs9DDxoQt4qnzq3Tf4/+s33jINVnEHA7A0WjU66MwAqzihn4VZm7F8LMoqz2nRWYKVgiZFAXoOUubaVshQHIlEq9YfisHXHsFQ2mg9DCptjdpa8m1Y1ZnsI9DmMQ/5Krztl5NAP/Al5WIZTJgkEs1nZdX455lr4HYuluaiCntqL+S4CgAqkpfprJfmaEAK70GZrk3TQFr10nATYsQuxtw34l7xY7mtx/hQDCJ3mV/1pXWSsH6u7LcjMz8osEN0jvtx2PB6MaM/NOOUTuuLAR2CekEvptNr1/RuesOSg8TO85Oen46tPFHh9K2DgYkj6Hy7lY3ihd8+Ykc1AonPeoq1mDiYrEpHWpVAxy9eWb5E0yPc9PEvd4gZ5aSy0j/QM+TeQB5Qj1oq/4xernB/BW4HysnZbaV0NaQvOPjadEIYJyFDSf4j7SplR7GhrcCUfyDJoj1wg3S8X/bhDyETCr7Mq3S+Mk/VMvHNUTkj9/LC7yp7Ni4vo4AYLkqfqf4R47TZ/qTqQNKfvLp/I=
  app: streetwalker-backend
  run: rails db:migrate
