before_install:
- gem install bundler
cache: bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: uCGMCHZ9XgD9wcd7Z06zb2PmLDdZ46QJGPDL9oeoegLazwjrny92q+/MWLsCngF8o00Ji/Br7PhKwrw9jS7ZkRAPvKIqipYW5isNEJO7j8ubN0+YNOIP88V4zpYNUfnfaDFm2lgJynJ07stUGCSSP2v4v+tk+5XZ5B5TfiPX5SYtj368mKojjgTMAjexEyvnWc8nq0QHaFrAq/+4rcWKlS57f4LB5u+8/cM2E5JvgpHj9mlgbZxWVKQfrOcZUoG/++BX0xZba+e2OXW4pYoJ/D6L+zYOqxu95o3yeJciHs+hV+9+lEJT0+f+uP9GH+iFxgXOav79N9BLVpEg3G1Zwq5xep8G3A1EYRd9dwtmwyB0IsB5qm2UQpvAfgH2iXzmF4k9ycTtsdp2FU8NYHT0byyuGdSt4IcukiquDwtgCR+a7eBsPdbHhA3DWSIcAHs5RjZKxj0InoRv2uma6gS9EzMJySDIMqqyygu/LI3JBKxalbKeRF8lQYR+pJ4amHCep0fdRTiGb/Btniv7IgZFKbAnWhlAPxF/dm9NVwuPrQmqndUSJjmJfzvaAmnkdnX3sice85bxIVBhYSOG/CjkrDl3QaruBPGdTsccqX5H6gPNUAuO/1hPM5QkWb/Fpf+Ky4wdYJ4jZ9x98ndntfOOpBPBkOKj2y+UdMhs2c5Q34Y=
  app: streetwalker-backend
  run: rails db:migrate
